# Generated by Django 2.2.5 on 2019-09-30 08:17

import bscore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=256)),
                ('problem', models.CharField(db_index=True, max_length=255)),
                ('problem_type', models.CharField(choices=[(bscore.models.ProblemTypeEnum('difference'), 'difference'), (bscore.models.ProblemTypeEnum('pythagorean_triplet'), 'pythagorean_triplet')], db_index=True, max_length=255)),
                ('occurrence', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
